version: "3.8"

services:
  back:
    container_name: raport_BACK
    build: ./back
    restart: on-failure:10
    environment:
      - DATABASE_URL=postgresql+psycopg2://docker:docker@postgres:5432/Artgeist_API
      - CORS_URL=http://localhost:3000
      - DB_TIMEOUT=30
    # - DATABASE_URL=postgresql://docker:hVD8n17wyTL76XW9NQuFD7fv1tmZsSzG@dpg-ch8i0m6si8uhth7qias0-a.frankfurt-postgres.render.com/artgeist_api
    ports:
      - 8000:8000
    networks:
      - app-network
    volumes:
      - ./back:/back/

  front:
    container_name: raport_FRONT
    build: ./front
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./front:/front/

networks:
  app-network:
    external:
      name: database-net
