version: "3.8"

services:
  db:
    container_name: database
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: Artgeist_API
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backend

  app:
    container_name: Raport_API
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - backend

      
networks:
  backend:
     driver: bridge
