version: "3.8"

services:
  app:
    container_name: Raport_API
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    