version: "3.8"

services:
  db:
    container_name: database
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: Artgeist_API
    networks:
      - backend

  adminer:
    container_name: database-adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backend

  back:
    container_name: Raport_BACK
    build: ./back
    depends_on:
      db:
        condition: service_started
    restart: on-failure:10
    environment:
      - DATABASE_URL=postgresql+psycopg2://docker:docker@db:5432/Artgeist_API
      - CORS_URL=http://localhost:3000
      - DB_TIMEOUT=30
    # - DATABASE_URL=postgresql://docker:hVD8n17wyTL76XW9NQuFD7fv1tmZsSzG@dpg-ch8i0m6si8uhth7qias0-a.frankfurt-postgres.render.com/artgeist_api
    ports:
      - 8000:8000
    networks:
      - backend

  front:
    container_name: Raport_FRONT
    build: ./front
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: bridge
